# permissions to do viewer eamilapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eamilapp-viewer-role
rules:
- apiGroups:
  - emailapp.lemon.cn
  resources:
  - eamilapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - emailapp.lemon.cn
  resources:
  - eamilapps/status
  verbs:
  - get
