
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - emailapp.lemon.cn
  resources:
  - eamilapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - emailapp.lemon.cn
  resources:
  - eamilapps/status
  verbs:
  - get
  - patch
  - update
