apiVersion: emailapp.lemon.cn/v1
kind: EamilApp
metadata:
  name: sinamail-cr
spec:
  # Add fields here
  appName: sinamail-app-server
  image: gdsz.harbor.com/experimental_images/nginx:v2
  containerPort: 80
  singlePodQPS: 400
  totalQPS: 1200
  cpuRequest: "200m"
  cpuLimit: "200m"
  memRequest: "128Mi"
  memLimit: "256Mi"
